# Generated by Django 5.2.4 on 2025-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Your Name', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
