# Generated by Django 5.2.4 on 2025-07-23 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(default="Dhaka", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(default="Your Name", max_length=150),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(default="Other", max_length=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
