# Generated by Django 5.2.4 on 2025-08-16 13:11

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('prescription_required', models.BooleanField(default=False)),
                ('image1', models.ImageField(upload_to='products/', validators=[users.models.validate_image_size])),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/', validators=[users.models.validate_image_size])),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/', validators=[users.models.validate_image_size])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='users.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
