# Generated by Django 5.2.4 on 2025-08-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('ml', 'ml'), ('g', 'g'), ('bottle', 'Bottle')], default='pcs', max_length=50),
        ),
    ]
