# Generated by Django 5.2.4 on 2025-08-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='adult_dose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='child_dose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='contraindication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='indication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='precaution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='side_effect',
            field=models.TextField(blank=True),
        ),
    ]
