# Generated by Django 5.2.4 on 2025-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_product_adult_dose_product_child_dose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_value',
            field=models.CharField(blank=True, help_text="Specify the quantity or volume (e.g., '5 ml', '2 tablets')", max_length=50, null=True),
        ),
    ]
