# Generated by Django 5.2.4 on 2025-08-17 11:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_product_unit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_quantity',
            field=models.CharField(blank=True, choices=[('strip', '1 Strip'), ('box', '1 Box'), ('pack', '1 Pack')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('mg', 'mg'), ('ml', 'ml'), ('g', 'g')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', validators=[users.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[users.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('bottle', 'Bottle')], default='pcs', max_length=50),
        ),
    ]
