# Generated by Django 5.2.4 on 2025-08-23 17:57

import cloudinary.models
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_cart_prescriptionrequest_prescriptionitem_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='prescription_request',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescriptionrequest',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='uniq_active_cart_per_user',
        ),
        migrations.RenameField(
            model_name='prescriptionrequest',
            old_name='admin_notes',
            new_name='admin_comment',
        ),
        migrations.RenameField(
            model_name='prescriptionrequest',
            old_name='approved_at',
            new_name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='prescription_request',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='auto_add_to_cart',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_requests', to='users.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='uploaded_image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, validators=[users.models.validate_image_size], verbose_name='prescription'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrescriptionItem',
        ),
    ]
