# Generated by Django 5.2.4 on 2025-08-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_order_payment_status_order_tran_id_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
