# Generated by Django 5.2.4 on 2025-08-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package_quantity',
            field=models.CharField(blank=True, choices=[('1 strip', '1 Strip'), ('1 box', '1 Box'), ('1 pack', '1 Pack')], max_length=20, null=True),
        ),
    ]
