# Generated by Django 5.2.4 on 2025-09-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_product_package_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tran_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
