# Generated by Django 5.2.4 on 2025-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_doctor_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(max_length=5),
        ),
    ]
