
web: gunicorn shasthomeds.wsgi:application \
  --workers 1 \
  --worker-class gthread \
  --threads 4 \
  --timeout 120 \
  --preload \
  --log-level info \
  --access-logfile - \
  --error-logfile -
